### ISSUE TITLE
Crash due to ipyfy

### ISSUE THREAD

**Issue by nithou** [ArnaudLevaufre/GandIP#1]
Hello!

For one month now I encounter this error when trying to run the script : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for '[api.ipify.org](http://api.ipify.org/)'.

Seems related to IPYFY, any idea how to bypass / fix it?

**Comment by ArnaudLevaufre** [comment]
Hello,
[api.ipify.org](https://api.ipify.org) works fine for me. You can update the provider url with the API endpoints provided by [seeip.org](https://seeip.org/) by changing [lines 32 and 33](https://github.com/ArnaudLevaufre/GandIP/blob/master/gandip.py#L32-L33):
```python
IPV4_PROVIDER_URL = "https://ip4.seeip.org/" 
IPV6_PROVIDER_URL = "https://ip6.seeip.org/"
```
Any other provider returning the IP as plain text should work fine. If you find a reliable provider that do not serve the response as plain text, you can update the function `get_current_ip` so it parses the response and returns a string representing the IP.

Unfortunately there are no option to customize the ip provider from the cli arguments. So you won't be able to use the packaged software for now.

I hope this helps.
